Treehouse.FitnessFrog/Controllers/EntriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Treehouse.FitnessFrog.Shared.Data;
using Treehouse.FitnessFrog.Shared.Models;
using Treehouse.FitnessFrog.ViewModels;

namespace Treehouse.FitnessFrog.Controllers
{
    public class EntriesController : Controller
    {
        private EntriesRepository _entriesRepository = null;
        private ActivitiesRepository _activitiesRepository = null;

        public EntriesController(EntriesRepository entriesRepository, ActivitiesRepository activitiesRepository)
        {
            _entriesRepository = entriesRepository;
            _activitiesRepository = activitiesRepository;
        }

        public ActionResult Index()
        {
            IList<Entry> entries = _entriesRepository.GetList();

            // Calculate the total activity.
            decimal totalActivity = entries
                .Where(e => e.Exclude == false)
                .Sum(e => e.Duration);

            // Determine the number of days that have entries.
            int numberOfActiveDays = entries
                .Select(e => e.Date)
                .Distinct()
                .Count();

            var viewModel = new EntriesIndexViewModel()
            {
                Entries = entries,
                TotalActivity = totalActivity,
                AverageDailyActivity = numberOfActiveDays != 0 ?
                    (totalActivity / numberOfActiveDays) : 0
            };

            return View(viewModel);
        }

        public ActionResult Add()
        {
            var viewModel = new EntriesAddViewModel();

            viewModel.Init(_activitiesRepository);

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(EntriesAddViewModel viewModel)
        {
            ValidateEntry(viewModel.Entry);

            if (ModelState.IsValid)
            {
                _entriesRepository.Add(viewModel.Entry);

                TempData["Message"] = "Your entry was successfully added!";

                return RedirectToAction("Index");
            }

            viewModel.Init(_activitiesRepository);

            return View(viewModel);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Entry entry = _entriesRepository.Get((int)id);

            if (entry == null)
            {
                return HttpNotFound();
            }

            var viewModel = new EntriesEditViewModel()
            {
                Entry = entry
            };
            viewModel.Init(_activitiesRepository);

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(EntriesEditViewModel viewModel)
        {
            ValidateEntry(viewModel.Entry);

            if (ModelState.IsValid)
            {
                _entriesRepository.Update(viewModel.Entry);

                TempData["Message"] = "Your entry was successfully updated!";

                return RedirectToAction("Index");
            }

            viewModel.Init(_activitiesRepository);

            return View(viewModel);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Entry entry = _entriesRepository.Get((int)id);

            if (entry == null)
            {
                return HttpNotFound();
            }

            return View(entry);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            _entriesRepository.Delete(id);

            TempData["Message"] = "Your entry was successfully deleted!";

            return RedirectToAction("Index");
        }

        private void ValidateEntry(Entry entry)
        {
            // If there aren't any "Duration" field validation errors
            // then make sure that the duration is greater than "0".
            if (ModelState.IsValidField("Duration") && entry.Duration <= 0)
            {
                ModelState.AddModelError("Duration",
                    "The Duration field value must be greater than '0'.");
            }
        }
    }
}

Treehouse.FitnessFrog/Views/Shared/_Layout.cshtml
@{ 
    var applicationName = "Fitness Frog";
}

@helper GetButtonVisibility(string controller, string action = null)
{
    if ((string)ViewContext.RouteData.Values["controller"] == controller &&
        (action == null || (string)ViewContext.RouteData.Values["action"] == action))
    {
        <text>hidden</text>
    }
    else
    {
        <text>visible</text>
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @applicationName</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon">
    <link href="~/favicon.ico" rel="icon" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Secular+One" rel="stylesheet">
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />*@
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Entries")">
                    @Html.Partial("_Logo", new ViewDataDictionary { { "element-id", "logo" } })
                    @applicationName
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
                <div class="navbar-right">
                    @if (Request.IsAuthenticated)
                    {
                        <a href="@Url.Action("Add", "Entries")"
                           style="visibility: @GetButtonVisibility("Entries", "Add")"
                           class="btn btn-primary navbar-btn">
                            <span class="glyphicon glyphicon-plus"></span> Add Entry
                        </a>
                        using (Html.BeginForm("SignOut", "Account", FormMethod.Post, new { @class = "navbar-right" }))
                        {
                            <button type="submit" class="btn btn-default navbar-btn">
                                <span class="glyphicon glyphicon-log-out"></span> Sign Out
                            </button>
                        }
                    }
                    else
                    {
                        <a href="@Url.Action("Register", "Account")"
                           style="visibility: @GetButtonVisibility("Account")"
                           class="btn btn-success navbar-btn">
                            <span class="glyphicon glyphicon-plus"></span> Register
                        </a>
                        <a href="@Url.Action("SignIn", "Account")"
                           style="visibility: @GetButtonVisibility("Account")"
                           class="btn btn-default navbar-btn">
                            <span class="glyphicon glyphicon-log-in"></span> Sign In
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <footer>
            @Html.Partial("_Logo", new ViewDataDictionary { { "element-id", "footer_logo" } })
            <p>&copy; @DateTime.Now.Year @applicationName, All Rights Reserved.</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-2.2.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>
    <script>
        $('input.datepicker').datepicker({
            format: 'm/d/yyyy'
        });
    </script>
</body>
</html>

Treehouse.FitnessFrog/Views/Shared/_Logo.cshtml
<svg id="@ViewData["element-id"]" viewBox="0 0 70.6 64.9" preserveAspectRatio="xMinYMin meet">
    <path d="M18.5,43.8c-1.4-2.7-5.1-3.3-7.3-1.1l-2.8,2.8c-2,2-1.7,5.3,0.6,7l17.4,12.2c1.2,0.8,2.6-0.5,2-1.7L18.5,43.8z" />
    <path d="M59.4,42.6c-2.2-2.2-5.9-1.6-7.3,1.1l-9.9,19.2c-0.7,1.3,0.8,2.6,2,1.7l17.4-12.2c2.3-1.6,2.6-5,0.6-7L59.4,42.6z" />
    <path d="M69.1,25.8h-5.3l4.4-4.4c0.6-0.6,0.6-1.5,0-2.1c-0.6-0.6-1.5-0.6-2.1,0l-4.4,4.4v-5.3c0-0.8-0.7-1.5-1.5-1.5
          		s-1.5,0.7-1.5,1.5v7.4H43.6L40.2,20l-3.9,14.3c-0.2,0.9-1.5,1-1.9,0.1l-5-12.1l-3.2,3.5H11.9v-7.4c0-0.8-0.7-1.5-1.5-1.5
          		s-1.5,0.7-1.5,1.5v5.3l-4.4-4.4c-0.6-0.6-1.5-0.6-2.1,0c-0.6,0.6-0.6,1.5,0,2.1l4.4,4.4H1.5c-0.8,0-1.5,0.7-1.5,1.5
          		s0.7,1.5,1.5,1.5h14.2L33.4,63c0.8,1.6,3.1,1.6,3.9,0l17.7-34.1h14.2c0.8,0,1.5-0.7,1.5-1.5S69.9,25.8,69.1,25.8z" />
    <path d="M29.3,17.9c0.5-0.5,1.4-0.4,1.7,0.3l4,9.6l3.6-13.2c0.2-0.9,1.4-1,1.8-0.2l4.9,8.5h9.1l-16-21.1c-1.7-2.2-4.6-2.2-6.3,0
          		l-16,21.1h8.7L29.3,17.9z" />
</svg>